# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('basket_datetime', models.DateTimeField(auto_now_add=True, verbose_name='time_of_addition')),
                ('basket_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CollectionsImg', verbose_name='product')),
                ('basket_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
